import enum


class PresentMonExitCodes (enum.Enum):

    STATUS_OK = 0
    GENERAL_ERROR = 1000
    EVENT_STREAMING_ALREADY_RUN_ERROR = 1001
    EVENT_STREAMING_SHOULD_QUIT_ERROR = 1002
    EVENT_STREAMING_IS_NOT_RUNNING_ERROR = 1003
    EVENT_STREAMING_STOP_ERROR = 1004
    INVALID_ARGUMENTS_ERROR = 1005
    BUFFER_IS_NOT_EMPTY_ERROR = 1006
    PRIVILIGIES_ERROR = 1007